---

- name: Install base needed yum-packages
  block:
    - name: Install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: Install base packages
      yum:
        name:
          - python3-devel
          - python3-virtualenv
          - python3-pip
          - tcl-devel
          - tk-devel
          - python36-tkinter
          - git
          - python36-virtualenv
        state: latest
