---
- name: nginx start
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    daemon_reload: yes
    enabled: yes
  become: yes
